name: intercargo
description: A new Flutter project

version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <4.0.0'  # Versão mais compatível

dependencies:
  flutter:
    sdk: flutter

  # Pacotes modernos null-safe:
  url_launcher: ^6.1.11
  mobile_scanner: ^6.0.7
  camera: ^0.11.1
  qr_flutter: ^4.1.0

  # Remova ou substitua estes pacotes problemáticos:
  # email_launcher: ^1.1.1  # Remover (usar url_launcher)
  # flutter_barcode_scanner: ^2.0.0  # Remover (usar mobile_scanner)
  # qr_code_scanner: ^1.0.1  # Remover (usar mobile_scanner)

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/