name: intercargo
description: A new Flutter project

version: 1.0.0+1

environment:
  sdk: '^3.7.0'

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.11.1
  email_launcher: ^1.1.1


  flutter_barcode_scanner: ^2.0.0
  qr_flutter: ^4.1.0
  qr_code_scanner: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/

